# Generated by Django 4.2.2 on 2023-08-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0003_taskcomment_task_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='owner',
            field=models.IntegerField(default=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.IntegerField(default=19),
        ),
    ]
