# Generated by Django 4.2.2 on 2023-09-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0007_costscategory_health_costs_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='sex',
        ),
        migrations.AddField(
            model_name='animal',
            name='sex',
            field=models.CharField(default='male/female', max_length=50),
        ),
    ]
