# Generated by Django 4.2.2 on 2023-09-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0009_remove_animal_costs_remove_animal_health_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
