# Generated by Django 4.2.2 on 2023-09-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0010_health_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
