# Generated by Django 4.2.2 on 2023-10-08 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0012_animal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='costs',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
