# Generated by Django 4.2.2 on 2023-10-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0015_health_created_at_vaccination_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
